name: Daily Pluto M3U Update

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 7 AM EST / 12:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    # Add this permissions block
    permissions:
      contents: write # Grant write permission to the GITHUB_TOKEN for this job

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        # If you intend GH_TOKEN to be a Personal Access Token (PAT)
        # you created yourself and stored as a secret, you might need
        # to explicitly pass it to checkout as well, though granting
        # the default token permissions is usually preferred.
        # with:
        #   token: ${{ secrets.GH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Pluto M3U
        run: node generateAllM3U.js

      - name: Commit and push
        run: |
          git config user.name github-actions[bot] # Use the bot name for clarity
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com # Use the standard bot email
          git add *.m3u
          # Check if there are changes staged for commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🔄 Daily update (Pluto M3U)"
            # Use the default GITHUB_TOKEN for authentication since we granted permissions
            # If you MUST use a specific PAT stored in GH_TOKEN, keep your original URL
            # But using the default token is generally simpler when permissions are set.
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
          fi
        # Consider adding error handling for the push if needed